version: '3.5'
services:
  cola_aqui_mysql:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: password
    ports:
      - "3306:3306"
    volumes:
      - cola_aqui_mysql_data:/var/lib/mysql
  cola_aqui_on_rails:
    build: .
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 3000 -b '0.0.0.0'"
    volumes:
      - .:/api
    ports:
      - "3000:3000"
    depends_on:
      - cola_aqui_mysql
    links:
      - cola_aqui_mysql
    environment:
      DB_USER: root
      DB_PASSWORD: password
      DB_HOST: cola_aqui_mysql
      API_KEY_HMAC_SECRET_KEY: 2e0d0c3fa6ce87007a291ed674d75646091a025931e5ecde8086751f1ccd1837

volumes:
  cola_aqui_mysql_data:
